### PR TITLE
About Page?

### PR DESCRIPTION
**Pull request by todd-lm**
I added an about page but, I have no idea if we need it. Feel free to accept this request!  @RobotXLabs @dacodingguy @apineapple @LEGOminer @c22ec

### CODE REVIEW

**Comment by amazansky** [comment]
Hi @Tpixelminer!
Great idea in theory, but not so great in practice.
Here's what I mean.
An example: so you changed "this site's terms..." to "c22coders terms..." This could indicate that by taking the profile page, you agree to the terms **or** that someone should change that to their own terms if they use the page.
Any thoughts, @c22coders?

**Comment by todd-lm** [comment]
Should I merge this? Like, IDK I think I'll merge it if there aren't any complaints or suggestions

**Comment by amazansky** [comment]
@Tpixelminer @c22coders/sample-profile-page 
I think this is ok!
Will merge if no objections

**Comment by todd-lm** [comment]
... So slow

**Comment by amazansky** [comment]
Merged

**Pull request merged**
