### PR TITLE
Todd edits

### PR DESCRIPTION
**Pull request by todd-lm**
Just ple MERGE!

### CODE REVIEW

**Comment by todd-lm** [comment]
Finally
I get it

Y U BE DIFFERENT MAC APP AND CONFUSE ME

**Comment by todd-lm** [comment]
So, basically. The idea of Github is:
- When you want to make a change you make a pull request/branch like #1 
- Then you commit changes, make a pull request
- Talk about it on the pull request then finally merge and BOOM!!!!

> wow
> @Tpixelminer

**Comment by todd-lm** [comment]
What I went through: 
screen shot 2016-05-24 at 5 04 45 pm

**Comment by amazansky** [comment]
Yay!
Glad you understand GitHub basics now.
😛

**Pull request merged**
